# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Captive Portal add-on
version: "0.0.1"
slug: captive-portal
description: Captive Portal add-on for use with UniFi Network.
url: "https://github.com/keytheengineer/add-ons/tree/main/captive-portal"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
#image: "ghcr.io/home-assistant/{arch}-addon-example"
